# DNC's insults vs Trump's own tweets

The DNC's account calls Trump "dumbass," "stupid," "gross," "ugly." How many of those are the account's own invention, and how many is it borrowing from Trump's own decade of insults?

The insult set is a curated lexicon (`curated_insults.csv`) I pulled by hand from the vetted "according to Dems" walls — every insult the account aimed at Trump and Vance, checked post by post against the video. Then I test each one two ways: does the word show up anywhere in Trump's ~46,000 archived tweets, and — separately — did Trump ever wield it as a personal insult himself, rather than a stray or quoted use? That second call is the harder one that a one-off LLM pass made - verdicts here: `trump_usage_llm.jsonl`. Both results live in `insult_lineage_audit_table.csv`, which this notebook reads.

## Setup

In [1]:
import pandas as pd
pd.set_option("display.max_rows", None)       # show every row — no truncated lists
pd.set_option("display.max_colwidth", None)   # show full cell text
from pathlib import Path

ROOT = Path.cwd()
for cand in (ROOT, *ROOT.parents):
    if (cand / "data" / "analysis" / "insult_lineage_audit_table.csv").exists():
        ROOT = cand; break
AN = ROOT / "data" / "analysis"

audit   = pd.read_csv(AN / "insult_lineage_audit_table.csv")
curated = pd.read_csv(AN / "curated_insults.csv")
usage   = pd.read_json(AN / "trump_usage_llm.jsonl", lines=True)
dunks   = pd.read_csv(AN / "dunk_lines.csv")

print(f"{len(curated)} curated insults; {len(audit)} rows in the audit table")
audit.head(4)

100 curated insults; 96 rows in the audit table

,term,target,register,in_trump_lexically,trump_weaponized,trump_verdict,trump_evidence,own_voice_uses,sample_dem_use,sample_post_id,note
0,ugly,trump,body,True,True,insult_at_person,@ noma2300 You must be kidding - I kicked both of their ugly assses!,8,Ugly ass truck,7.480658e+18,NaN
1,fat,trump,body,True,True,insult_at_person,"Why would Kim Jong-un insult me by calling me 'old,' when I would NEVER call him 'short and fat?' Oh well, I try so…",11,"You've called women you don't like, ""fat pigs,""",7.418643e+18,NaN
2,fatty,trump,body,False,False,never_tweeted,NaN,1,fatty alert,7.636513e+18,NaN
3,tiny,trump,body,True,True,insult_at_person,Mini Mike is a short ball (very) hitter. Tiny club head speed. KEEP AMERICA GREAT! https://t.co/5DUj16jtZf,1,why does Trump look so tiny 😂,7.526391e+18,NaN

## §1 — The curated lexicon, by register

The lexicon is hand-pulled from the vetted walls, not from a keyword scanner — an earlier ~25-word scan missed most of it. I group it by register (body / mind / morals, plus a Vance-only subservience set), because that grouping is what the rest of the analysis turns on.

In [2]:

curated.groupby("register")["term"].agg(n="size", terms=lambda s: ", ".join(sorted(s)))

,n,terms
register,,
body,22,"bad hair, bad posture, creature, crusty, decaying, decaying sack of flesh, decrepit, fat, fatty, gross, mouth breather, nasty, repulsive, scaly, snorlax, sweaty, tan, tiny, too many chins, ugly, wig, wrinkled"
mind,31,"80-year-old man, can't read, chopped, confused, cooked, crashing out, deteriorating, dumb, grandpa, insane, insecure, low energy, mad, melts down, mess, mogged, old, old as fart, oldest, rambling, sad sack, senile, sleepy, snoozing, stupid, unc, unhinged, unstable, unwell, useless, weird"
morals,33,"chicken, chud, convicted felon, diabolical, disgusting, epstein's bff, evil, fat chud, fat little chud, flop, haunted, horny, jealous, jobless, liar, loony bin, looter, loser, nightmare, pigging out, predator, rat, resident evil, sleep-paralysis demon, snowflake, spooky, tacky, tacky gold, traitor, true chud, vile, wannabe dictator, worst"
subservience,14,"bootlicker, concerning, creep, disgusting, dumb, irrelevant, jd-chan, mad, negative aura, owned, poor, sellout, ugly bootlicker, weird"

## The walls these come from

The lexicon above is distilled from the walls I vetted by hand: every insult @democrats aimed at Trump and Vance, pulled from captions, on-screen text and transcripts, checked post by post. Here they are in full — parsed straight from `walls_print.md`.

In [3]:
import re

text = (ROOT / "data" / "walls_print.md").read_text()
sections = {"Trump, according to Dems": "trump", "Vance, according to Dems": "vance"}

rows = []
for section in text.split("## ")[1:]:
    head = section.split("\n", 1)[0].strip()
    if head not in sections:
        continue
    for line in section.splitlines():
        m = re.match(r"\s*(20\d\d)(?:\s*\(through July\))?\s+(.*)", line)
        if not m:
            continue
        year, body = m.group(1), m.group(2)
        for snippet in re.split(r"\s{2,}", body):     # wall lines are separated by 2+ spaces
            snippet = snippet.strip(" *")
            if len(snippet) > 1 and snippet != "—":
                rows.append({"target": sections[head], "year": year, "line": snippet})

walls = pd.DataFrame(rows)
print("wall lines:", walls.groupby("target").size().to_dict())
walls

wall lines: {'trump': 264, 'vance': 26}

,target,year,line
0,trump,2023,60 seconds of Donald Trump blabbing... 🤴🦞💨🐋🤡
1,trump,2023,we're glad you lost
2,trump,2023,Flop.
3,trump,2023,THUNDA
4,trump,2023,Is Donald Trump... okay?🤡
5,trump,2024,A deeply confused Trump confuses Nancy Pelosi and Nikki Haley multiple times
6,trump,2024,oh brother this guy stinks
7,trump,2024,Them being weird
8,trump,2024,"Republicans Are Weird... These are weird people on the other side. Listen to them speak. These are weird ideas. [Trump moans] These are weird, weird people. Don't get sugarcoating."
9,trump,2024,every presidential candidate has their strange wannabe
10,trump,2024,when you're a convicted felon who got smoked at the debate and is going to lose the election
11,trump,2024,He's cooked
12,trump,2024,"They're laughing at you Donald, not with you!"
13,trump,2024,POV people leaving Trump's rally because he won't stop rambling about sharks & windmills
14,trump,2024,Trump is a 🐔
15,trump,2024,"Uh, what is he saying??"
16,trump,2024,Trump: “I have the best words” 🤔
17,trump,2024,"A second Trump term, more unhinged, unstable and unchecked."
18,trump,2024,What's going on with his tan 😭
19,trump,2024,Funny you should say that...
20,trump,2024,someone's sleepy
21,trump,2024,Tim Walz: Donald Trump looks like Ronald McDonald 🤡
22,trump,2024,who's the oldest presidential nominee in history?
23,trump,2024,"""I'd like a natural tan please"""
24,trump,2024,Rogan laughs in Trump's face 😂🫵
25,trump,2024,"how I'll look on election day knowing I didn't vote for the old, crusty, convicted felon, wannabe dictator 💅"
26,trump,2024,I think Trump is... jealous? 😘
27,trump,2024,Trump with his... 🥴
28,trump,2024,Trump doesn't even know what he's talking about anymore 🤣🥴
29,trump,2024,Is Donald Trump ok???
30,trump,2024,SPOOKY!
31,trump,2024,Trump is increasingly unhinged!
32,trump,2024,"What could be worse than the Mr. Evil guy? ""Me is worse"", said the Mr. Super evil guy Little did he know about Larry"
33,trump,2024,Evil kitty
34,trump,2025,SNOWFLAKE
35,trump,2025,Vice President Trump brings out President Musk 🤭
36,trump,2025,bro is definitely not mad
37,trump,2025,Trump standing by his president 🤭🤭🤭
38,trump,2025,"bro literally called TikTok ""tic tac"" two times ☠️"
39,trump,2025,bro is cooked 😭
40,trump,2025,a sad little Trump letting President Musk control his first Cabinet meeting 🤣🤣
41,trump,2025,lol Trump already is getting dunked on at the joint address 🤣
42,trump,2025,bro is CRASHING OUT
43,trump,2025,Trump MELTS DOWN after reporter fact-checks him 😩
44,trump,2025,Trump MELTS DOWN after finding out Wall Street calls him a chicken behind his back 😭
45,trump,2025,He's so mad lol 🐔
46,trump,2025,"""Sounds like a fourth grader came up with it"" 💀"
47,trump,2025,"""Oh, man, the girls are fighting, aren't they?"""
48,trump,2025,Trump tripped on the AF1 stairs lol
49,trump,2025,his posture 😭
50,trump,2025,Trump's UNHINGED flagpole rant 😭😭
51,trump,2025,he wants melania's job so bad 😭
52,trump,2025,Trump says he might deport Elon 😭
53,trump,2025,Shameful.
54,trump,2025,if you're in the files just say that😭
55,trump,2025,Oh he's maddddd😭
56,trump,2025,why does Trump look so tiny 😂
57,trump,2025,Trump is now admitting his Epstein deflection tactics 😭
58,trump,2025,he's crashing out 😭
59,trump,2025,just found out I am chopped and also unc
60,trump,2025,Keir Starmer's reaction to Trump rambling about windmills 😅
61,trump,2025,got bored and turned myself into a mar-a-lago
62,trump,2025,🍊🍬
63,trump,2025,is he asleep??
64,trump,2025,Trump keeps saying something strange
65,trump,2025,now why tf was Trump wandering around on the White House roof 💀
66,trump,2025,Trump's Education Secretary interrupted by circus music 🤡
67,trump,2025,pls trump's oval office is so tacky 😭☝️
68,trump,2025,she's got a wig ✨
69,trump,2025,get the hell out of DC 🙂‍↕️
70,trump,2025,YOU JUST GOT KRISSED BITCH!!! 😝😜😚👉👉👉👉
71,trump,2025,what is bro talking about 😭
72,trump,2025,What is he talking about ?? 😭
73,trump,2025,commander in chopped
74,trump,2025,Hand looking chopped 😳
75,trump,2025,What is bro going on about? 😭
76,trump,2025,how Trump sounds when he rambles about nonsense 😀
77,trump,2025,Princess Diaries but if Mia was chopped and unc
78,trump,2025,bro's just saying anything atp 😭😭
79,trump,2025,bro can't pronounce acetaminophen 😭
80,trump,2025,Trump rambling to the UN 😀
81,trump,2025,low energy. sad!
82,trump,2025,bro's still at it
83,trump,2025,it's been days and Trump's still ranting about the UN teleprompter
84,trump,2025,"""THE PRESIDENT IS UNHINGED. HE IS UNWELL."""
85,trump,2025,does he even know what year it is??
86,trump,2025,"""THIS IS A CONVICTED FELON, I MEAN THINK ABOUT THAT, WHO IS THREATENING TO JAIL ME. I GOTTA SAY THIS GUY'S UNHINGED, HE'S INSECURE, HE'S A WANNABE DICTATOR."""
87,trump,2025,lmao trump could hardly keep his eyes open today
88,trump,2025,let's get you to bed grandpa 😴
89,trump,2025,this trend but wtf is he doing
90,trump,2025,trump rn: [sad hamster meme]
91,trump,2025,not Trump crashing out abt Time using this chopped pic of him 😭
92,trump,2025,"Trump, 79, goes on unhinged rant about ""reverse bath tubs"""
93,trump,2025,Trump's showing off his toy models to an audience of billionaire donors
94,trump,2025,guys trump's mcdonald's order just leaked and it's completely diabolical ➡️ he combines a filet o fish with a burger 🤢🤢🤢
95,trump,2025,when he can't read 😍
96,trump,2025,sometimes you just gotta read what trump is posting and move on with your day
97,trump,2025,wtf is this new mob
98,trump,2025,bruh
99,trump,2025,am i making you feel sick?
100,trump,2025,"how to make your photo look straight out of the upside down... go to filters ➡️ retro ➡️ pumpkin, put it to 100"
101,trump,2025,this trend but wtf is he doing
102,trump,2025,"1 girl, 10 obsessions... 6. orange makeup"
103,trump,2025,what is bro talking about 😭😭
104,trump,2025,time and place!!!
105,trump,2025,Spongebob big guy pants ok
106,trump,2025,mogged
107,trump,2025,"Yeah, he's lost man. He doesn't know what the fuck to do."
108,trump,2025,mogged
109,trump,2025,on today's episode of fat and jobless
110,trump,2025,A SAD SACK
111,trump,2025,Constitution — It has a lot of big words he doesn't understand
112,trump,2025,More of a tacky gold guy!
113,trump,2025,"A RAT IS A TRAITOR, A RAT IS A F**KING RAT"
114,trump,2025,Trump loves WHAT??
115,trump,2025,-sleepy -orange -tweeting all day and night -bored af
116,trump,2025,sleeping during his own event again 🤨
117,trump,2025,is he good lol
118,trump,2026,listen here dingbat
119,trump,2026,Trump said WHAT????
120,trump,2026,WHAT IS THAT CREATURE? SCIENTIFIC NAME
121,trump,2026,DONALD JOHN TRUMP
122,trump,2026,COMMONLY REFERRED TO AS UGLY :(
123,trump,2026,mogged
124,trump,2026,wtf is wrong with him
125,trump,2026,american horror story
126,trump,2026,imagine leaving your house looking like that
127,trump,2026,look how cute 🤗
128,trump,2026,ugly
129,trump,2026,bad hair
130,trump,2026,falling asleep on the job
131,trump,2026,predator
132,trump,2026,stupid
133,trump,2026,fondling microphones
134,trump,2026,too many chins
135,trump,2026,wrinkled clothing
136,trump,2026,bad posture
137,trump,2026,defamation
138,trump,2026,destruction
139,trump,2026,negligence
140,trump,2026,indicted for racketeering
141,trump,2026,lollygagging
142,trump,2026,begging
143,trump,2026,mouth breather
144,trump,2026,epstein's bff
145,trump,2026,I AM NOT CUTE I AM NOT BEAUTIFUL I AM NOT INTELLIGENT I AM NOT PERFECT
146,trump,2026,quinn hughes just saw the scariest ghost yet
147,trump,2026,haunted.
148,trump,2026,MOGGED
149,trump,2026,Liar
150,trump,2026,A liar is someone who intentionally says a false statement. Donald Trump does not protect American citizens. As seen in January when his federal agents killed two citizens in Minneapolis.
151,trump,2026,Loser
152,trump,2026,"Someone who is defeated in a contest, competition, or game. Democrats have won or overperformed in 251 elections, which means the Republicans are not winning ""so much."""
153,trump,2026,Looter
154,trump,2026,"Someone who steals goods. People were not lifted off food stamps, they were kicked off. Perhaps those funds went to the Trump family's pockets."
155,trump,2026,this trend but it's the commander in chopped
156,trump,2026,liar.
157,trump,2026,best friends 🤢
158,trump,2026,bro falling asleep AGAIN 😭😭
159,trump,2026,gross
160,trump,2026,nasty
161,trump,2026,my face a 10
162,trump,2026,my body tea
163,trump,2026,everything on me natural
164,trump,2026,i'm petite
165,trump,2026,and I got some pretty feet
166,trump,2026,"i'm the perfect mix of fucking up the economy [and] weird, scaly neck rash and rapidly decaying hand"
167,trump,2026,i know what you really like! florsheim leather oxford dress shoes ballrooms tacky gold diet coke mamdani epstein mcdonald's filet-o-fish orange makeup jake paul's sweaty pits
168,trump,2026,new decrepit hand pic dropped 😍
169,trump,2026,this guy is so fucking horny
170,trump,2026,he's repulsive
171,trump,2026,this mfer interrupted survivor AGAIN 😭
172,trump,2026,someone tell him to stfu
173,trump,2026,this show sucks
174,trump,2026,this zombie mod fcking sucks
175,trump,2026,it won't despawn
176,trump,2026,trump holds easter bunny hostage while rambling about planes 😭
177,trump,2026,outfit inspo
178,trump,2026,how trump feels going outside with his nasty rash and hand bruise
179,trump,2026,Trump crashing out over the MAGA influencers who hate him now 😭
180,trump,2026,DOES THIS LOOK LIKE A DOCTOR TO YOU?
181,trump,2026,Trump goes on unhinged rant attacking Pope Leo XIV
182,trump,2026,looking ugly per usual
183,trump,2026,he's old as fart
184,trump,2026,orange makeup hallelujah
185,trump,2026,he was so happy to be a mess
186,trump,2026,trump whenever the American people ask for help affording gas and groceries
187,trump,2026,always snoozing
188,trump,2026,senile
189,trump,2026,trump crashes tf out of his mic volume
190,trump,2026,someone turn off the mic 😭
191,trump,2026,spot the difference.... [Photo of Trump] [Photo of Jabba the Hutt] ...you can't
192,trump,2026,fatty alert
193,trump,2026,fits right in 😍
194,trump,2026,dawg what is he doing 😭
195,trump,2026,so bad Americans believe in ghosts more than Trump 😭
196,trump,2026,THUNDAH
197,trump,2026,no thanks ❤️
198,trump,2026,thought it was snorlax 😞
199,trump,2026,Apt. 666
200,trump,2026,Loony Bin
201,trump,2026,he dgaf
202,trump,2026,Evil fat lady.
203,trump,2026,he's old and decaying
204,trump,2026,horror movie
205,trump,2026,RESIDENT EVIL
206,trump,2026,fee fi fo fum
207,trump,2026,LEGENDARY LOVERS
208,trump,2026,anything but helping americans
209,trump,2026,disgusting.
210,trump,2026,worst bombshell ever
211,trump,2026,and they still look dumb
212,trump,2026,nightmare
213,trump,2026,evil.
214,trump,2026,"me, i treat him like he disgusting!"
215,trump,2026,BFF4L
216,trump,2026,evil 🤝 evil
217,trump,2026,Fat chud rules (as written by Donald J. Trump)
218,trump,2026,true chuds hate their children
219,trump,2026,be super ugly and fat
220,trump,2026,true chuds love to prank!
221,trump,2026,get his dumbass outta here 🗣️
222,trump,2026,get trump OUT of the villa bruh 😂🥀
223,trump,2026,the worst
224,trump,2026,trump pigging out at the nba finals while no one can afford groceries
225,trump,2026,looks stupid af🥀
226,trump,2026,Achievement Made! Man's Best Friend [photo of Epstein and him]
227,trump,2026,Sweet Dreams [photo of him sleeping]
228,trump,2026,Bad Omen [photo of his bruise]
229,trump,2026,Maximum Capacity [photo of his body]
230,trump,2026,Balanced Diet? [photo of him eating]
231,trump,2026,Locked Up [his mugshot]
232,trump,2026,happy 80th birthday to this decaying sack of flesh❤️
233,trump,2026,the retirement home is calling
234,trump,2026,her and trump are having a wig off 😭😭😭
235,trump,2026,mfer showing off a pile of dirt that is costing taxpayers $300 million
236,trump,2026,nobody wants him!!!
237,trump,2026,why is trump acting like he's on love island 😭
238,trump,2026,rarest species of chud
239,trump,2026,i am a chud 🥰 i am a chud 🤣 i'm a fat little chud 🤯 i am a chud 🤩 i am a chud 🤪 i am a fat little chud 🤗
240,trump,2026,evil
241,trump,2026,can't wait for trump's posture to be fixed after his July 3rd appointment at rowley family chiropractic!
242,trump,2026,he relaxed his face completely and took a pic
243,trump,2026,jumpscare!
244,trump,2026,president of Türkiye helping trump walk in a straight line 💀
245,trump,2026,bro has no idea what is going on
246,trump,2026,nightmare sleep paralysis demon 😭😭
247,trump,2026,evil in a dif universe
248,trump,2026,disgusting
249,trump,2026,trump is literally deteriorating 😳
250,trump,2026,retirement home NOW
251,trump,2026,bro thinks he's on the team
252,trump,2026,trump falling asleep highlights reel
253,trump,2026,is he ever awake?
254,trump,2026,useless!
255,trump,2026,why is he so sweaty 😭😭
256,trump,2026,bruh
257,trump,2026,the plot has been lost
258,trump,2026,why on EARTH is an 80 yr old man saying this 🫪
259,trump,2026,80 year old man btw
260,trump,2026,thoughts and prayers 🙏
261,trump,2026,he needs an app blocker
262,trump,2026,he is vile
263,trump,2026,evil beyond belief.
264,vance,2024,Tim Walz owned JD Vance 🔥
265,vance,2024,Them being weird
266,vance,2024,us watching JD Vance trying to behave at all like a normal person
267,vance,2024,Vance got mad he was fact-checked 🤭
268,vance,2024,"""Me is worse"", said the Mr. Super evil guy"
269,vance,2025,JD VANCE TWO WEEKS AGO
270,vance,2025,🧎 JD VANCE NOW 🧎
271,vance,2025,@J.D. Vance wya
272,vance,2025,where is JD Vance bro 😭🤣
273,vance,2025,jd wya? 🤔
274,vance,2025,"jd-chan? what are some facts about you? sold out to trump, became completely irrelevant in a disastrous administration"
275,vance,2025,why does JD run like this 😭
276,vance,2025,"JD Vance: ""you guys have to clap and cheer at everything that I say"" 🥴"
277,vance,2025,negative aura
278,vance,2026,RUSSIA'S ILYA ROZANOV
279,vance,2026,competing for # 1 bootlicker
280,vance,2026,JD Vance refuses to apologize to Alex Pretti's family
281,vance,2026,disgusting.
282,vance,2026,do I creep you out?
283,vance,2026,'I'm a Never Trump guy' but you'll always be an ugly bootlicker ✨
284,vance,2026,you'll always find your way back home ✨
285,vance,2026,poor jd 😞
286,vance,2026,JD👎
287,vance,2026,and they still look dumb
288,vance,2026,JD Vance admits Joe Biden eating ice cream makes him think of sex
289,vance,2026,concerning

## How the lexicon maps to the walls

Every term in the lexicon traces back to real wall lines. This counts, for each term, how many wall lines it appears in — the distilled list and its vetted source side by side. A few phrase-form terms show 0 because they read differently in the wall than as a single keyword.

In [4]:
def wall_lines_for(term, target):
    w = walls[walls["target"] == target]
    hit = w["line"].str.contains(rf"\b{re.escape(term)}\b", case=False, regex=True)
    return w.loc[hit, "line"].tolist()

curated["wall_lines"] = [len(wall_lines_for(t, tg))
                         for t, tg in zip(curated["term"], curated["target"])]

# to read the actual lines behind any term:  wall_lines_for("ugly", "trump")
curated[["term", "target", "register", "wall_lines"]].sort_values("wall_lines", ascending=False)

                      term target      register  wall_lines
53                    evil  trump        morals           9
24                unhinged  trump          mind           7
50                 chopped  trump          mind           6
1                      fat  trump          body           5
40                     old  trump          mind           5
52                  mogged  trump          mind           4
31                rambling  trump          mind           4
28            crashing out  trump          mind           4
0                     ugly  trump          body           4
5                 decaying  trump          body           3
58         convicted felon  trump        morals           3
82                   tacky  trump        morals           3
62                    liar  trump        morals           3
64              disgusting  trump        morals           3
47                   weird  trump          mind           3
65                    chud  trump        morals           3
59        wannabe dictator  trump        morals           2
38                  sleepy  trump          mind           2
83              tacky gold  trump        morals           2
46                  stupid  trump          mind           2
29              melts down  trump          mind           2
27                     mad  trump          mind           2
87              bootlicker  vance  subservience           2
75               nightmare  trump        morals           2
23                  cooked  trump          mind           2
51                     unc  trump          mind           2
19                     wig  trump          body           2
18                   nasty  trump          body           2
63                   worst  trump        morals           2
14                     tan  trump          body           2
12                  sweaty  trump          body           2
69                   horny  trump        morals           1
66                fat chud  trump        morals           1
70               snowflake  trump        morals           1
61                   loser  trump        morals           1
71                 chicken  trump        morals           1
72                    flop  trump        morals           1
73                  spooky  trump        morals           1
74                 haunted  trump        morals           1
68         fat little chud  trump        morals           1
9              bad posture  trump          body           1
77           resident evil  trump        morals           1
91           negative aura  vance  subservience           1
98                   owned  vance  subservience           1
97              concerning  vance  subservience           1
96                   creep  vance  subservience           1
95              disgusting  vance  subservience           1
94                    dumb  vance  subservience           1
93                    poor  vance  subservience           1
92                 jd-chan  vance  subservience           1
90              irrelevant  vance  subservience           1
78               loony bin  trump        morals           1
88         ugly bootlicker  vance  subservience           1
86                   weird  vance  subservience           1
85                 jobless  trump        morals           1
84             pigging out  trump        morals           1
60                  looter  trump        morals           1
80           epstein's bff  trump        morals           1
79              diabolical  trump        morals           1
81                 jealous  trump        morals           1
54                    vile  trump        morals           1
57                 traitor  trump        morals           1
56                     rat  trump        morals           1
33                insecure  trump          mind           1
32                  unwell  trump          mind           1
6                 decrepit  trump          body           1
30              low energy  trump          mind           1
7                 wrinkled  trump          body           1
25                unstable  trump          mind           1
8           too many chins  trump          body           1
22                confused  trump          mind           1
21                creature  trump          body           1
20                 snorlax  trump          body           1
17                   gross  trump          body           1
16               repulsive  trump          body           1
15  decaying sack of flesh  trump          body           1
13                  crusty  trump          body           1
11          mouth breather  trump          body           1
34                  senile  trump          mind           1
35           deteriorating  trump          mind           1
36                 useless  trump          mind           1
37                snoozing  trump          mind           1
55                predator  trump        morals           1
10                bad hair  trump          body           1
2                    fatty  trump          body           1
3                     tiny  trump          body           1
4                    scaly  trump          body           1
49                sad sack  trump          mind           1
48                    mess  trump          mind           1
45                    dumb  trump          mind           1
44              can't read  trump          mind           1
43             old as fart  trump          mind           1
41                  oldest  trump          mind           1
39                 grandpa  trump          mind           1
99                     mad  vance  subservience           1
89                 sellout  vance  subservience           0
26                  insane  trump          mind           0
67               true chud  trump        morals           0
42         80-year-old man  trump          mind           0
76   sleep-paralysis demon  trump        morals           0

## §2 — Where each insult was used

`own_voice_uses` counts only the account's own caption or on-screen text — a song lyric or a quoted
clip doesn't count. The most-used words are the account's signatures.

In [5]:

(audit[audit["own_voice_uses"] > 0]
   .sort_values("own_voice_uses", ascending=False)
   [["term", "target", "register", "own_voice_uses"]]
   .head(15).reset_index(drop=True))

               term target register  own_voice_uses
0              chud  trump   morals              12
1               fat  trump     body              11
2              ugly  trump     body               8
3          fat chud  trump   morals               8
4             worst  trump   morals               8
5            cooked  trump     mind               7
6             weird  trump     mind               7
7            mogged  trump     mind               6
8              evil  trump   morals               6
9   convicted felon  trump   morals               5
10              tan  trump     body               5
11              old  trump     mind               5
12          chopped  trump     mind               4
13       disgusting  trump   morals               4
14         rambling  trump     mind               4

## §3 — Which of these words also show up in Trump's tweets

`in_trump_lexically` just means the word appears at least once in Trump's archived tweets. It's presence only — it doesn't yet mean he used it as an insult (§3b sorts that out). Obvious false friends, like the surname "Tan" for "tan," were pulled out by hand when the table was built.

In [6]:

print("Curated insults appearing lexically in Trump's tweets:",
      f"{audit['in_trump_lexically'].sum()} of {len(audit)}")

# the split by register
pd.crosstab(audit["register"], audit["in_trump_lexically"], margins=True)

Curated insults appearing lexically in Trump's tweets: 54 of 96

in_trump_lexically  False  True  All
register
body                   11    11   22
mind                    9    22   31
morals                 18    15   33
subservience            4     6   10
All                    42    54   96

## §3b — But did Trump actually weaponize the word?

Lexical presence over-counts. "Tiny" shows up in his tweets, but did he aim it at a person? A one-off LLM pass read his own uses and judged each shared word; the verdicts are cached. `trump_weaponized` is the final call — my overrides baked in — that Trump used the word as a personal insult, backed by a specific tweet.

In [7]:

print("Lexically present :", audit["in_trump_lexically"].sum())
print("Actually weaponized:", audit["trump_weaponized"].sum())

# the corrected split, by register
(audit[audit["trump_weaponized"]]
   .groupby("register")["term"].agg(n="size", terms=lambda s: ", ".join(sorted(s))))

Lexically present : 54
Actually weaponized: 37

,n,terms
register,,
body,7,"creature, decaying, fat, gross, nasty, tiny, ugly"
mind,15,"can't read, confused, dumb, insane, insecure, low energy, mad, rambling, sad sack, sleepy, stupid, unhinged, unstable, useless, weird"
morals,10,"disgusting, evil, flop, jealous, liar, loser, rat, traitor, vile, worst"
subservience,5,"creep, irrelevant, owned, poor, sellout"

In [8]:

# a few weaponized words with Trump's own supporting tweet
(usage[usage["used_as_insult"]]
   .merge(audit[["term"]], left_on="word", right_on="term")
   [["word", "evidence_tweet"]].head(8))

,word,evidence_tweet
0,ugly,@ noma2300 You must be kidding - I kicked both of their ugly assses!
1,fat,"Why would Kim Jong-un insult me by calling me 'old,' when I would NEVER call him 'short and fat?' Oh well, I try so…"
2,tiny,Mini Mike is a short ball (very) hitter. Tiny club head speed. KEEP AMERICA GREAT! https://t.co/5DUj16jtZf
3,decaying,Crazy Nancy Pelosi should spend more time in her her decaying city and less time on the Impeachment Hoax!
4,gross,"The @ HuffingtonPost is a total joke & laughing stock of journalism, as is gross Arianna Huffington. They don‚Äôt report the facts!"
5,nasty,"All polls have me winning debate big- Drudge, TIME, etc. Dopey Charles Krauthammer still nasty. He has zero cred- totally dishonest!"
6,creature,"Two months in jail for a Swamp Creature, yet 9 years recommended for Roger Stone (who was not even working for the Trump Campaign). Gee, that sounds very fair! Rogue prosecutors maybe? The Swamp! @foxandfriends @TuckerCa"
7,confused,Hillary Clinton answered email questions differently last night than she has in the past. She is totally confused. Unfit to serve as # POTUS.

## §3d — The wall: words the DNC used on Trump that Trump used on people himself

This is the "what went around came around" set — insults aimed at Trump that Trump himself weaponized. Two words pass the mechanical test but come out on review, with the reason next to each:

- **insane** — the account never cleanly calls *Trump* insane; its uses are crowd praise ("insane lineup") or a Vance line, so the Democratic side of the pairing fails.
- **evil** — Trump's cleanest "evil" aims at the media / "Fake News," not a person, and the tweet turns positive; it isn't a clean personal insult.

That leaves the 30 the story stands on.

In [9]:

# the two reviewed drops, with the reason kept beside each
DROP = {
    "insane": "account's uses are crowd praise / a Vance line, not a clean shot at Trump",
    "evil":   "Trump's 'evil' aims at the media, not a person; not a clean personal insult",
}
weaponized = audit[(audit["target"] == "trump") & (audit["trump_weaponized"])]
wall = weaponized[~weaponized["term"].isin(DROP)]

print(f"{len(weaponized)} words passed the mechanical test;",
      f"{len(DROP)} dropped on review; {len(wall)} in the wall.\n")
print("dropped on review:")
for term, reason in DROP.items():
    print(f"   x {term}: {reason}")

wall[["term", "register", "own_voice_uses", "sample_dem_use"]].reset_index(drop=True)

32 words passed the mechanical test; 2 dropped on review; 30 in the wall.

dropped on review:
   x insane: account's uses are crowd praise / a Vance line, not a clean shot at Trump
   x evil: Trump's 'evil' aims at the media, not a person; not a clean personal insult

,term,register,own_voice_uses,sample_dem_use
0,ugly,body,8,Ugly ass truck
1,fat,body,11,"You've called women you don't like, ""fat pigs,"""
2,tiny,body,1,why does Trump look so tiny 😂
3,decaying,body,2,"weird, scaly neck rash and rapidly decaying hand"
4,gross,body,1,gross
5,nasty,body,2,how trump feels going outside with his nasty rash and hand bruise
6,creature,body,1,WHAT IS THAT CREATURE?
7,confused,mind,2,*Confused*
8,unhinged,mind,4,UNHINGED
9,unstable,mind,3,UNSTABLE
10,mad,mind,4,Vance got mad he was fact-checked 😅
11,low energy,mind,1,low energy. sad!
12,rambling,mind,4,20 seconds of rambling
13,insecure,mind,1,HE'S INSECURE
14,useless,mind,1,useless!
15,sleepy,mind,1,someone’s sleepy
16,can't read,mind,1,when he can't read 😩
17,dumb,mind,1,and they still look dumb
18,stupid,mind,3,by saying something stupid like...
19,weird,mind,7,"If I had a nickel for every time a Republican candidate for speaker lost on the first vote this year, I'd have two nickels! Which isn't a lot... But it's weird that it happened twice, right?"
20,sad sack,mind,1,A SAD SACK
21,vile,morals,0,"(in walls, not tagged as a dunk line)"
22,rat,morals,0,"(in walls, not tagged as a dunk line)"
23,traitor,morals,0,"(in walls, not tagged as a dunk line)"
24,loser,morals,4,accepting that I'm a loser and Joe Biden beat me in 2020
25,liar,morals,1,liar.
26,worst,morals,8,Heartbreaking: The Worst Person You Know Just Made A Great Point
27,disgusting,morals,4,"""dogs,"" ""slobs,"" and ""disgusting animals."""
28,flop,morals,3,Flop.
29,jealous,morals,1,I think Trump is... jealous? 😘

## §4 — The full per-insult audit table

Every curated insult with all its verdicts in one place — lexical presence, whether Trump weaponized it, the own-voice count, a Trump evidence tweet, and any note. This is the spine; change `curated_insults.csv` and rebuild to update everything downstream.

In [10]:

audit[["term", "target", "register", "in_trump_lexically", "trump_weaponized",
       "own_voice_uses", "note"]]

,term,target,register,in_trump_lexically,trump_weaponized,own_voice_uses,note
0,ugly,trump,body,True,True,8,NaN
1,fat,trump,body,True,True,11,NaN
2,fatty,trump,body,False,False,1,NaN
3,tiny,trump,body,True,True,1,NaN
4,scaly,trump,body,False,False,1,NaN
5,decaying,trump,body,True,True,2,NaN
6,decrepit,trump,body,True,False,1,NaN
7,wrinkled,trump,body,False,False,0,NaN
8,too many chins,trump,body,False,False,0,NaN
9,bad posture,trump,body,False,False,0,NaN
10,bad hair,trump,body,False,False,0,NaN
11,mouth breather,trump,body,False,False,0,NaN
12,sweaty,trump,body,False,False,1,NaN
13,crusty,trump,body,False,False,1,NaN
14,tan,trump,body,True,False,5,NaN
15,decaying sack of flesh,trump,body,False,False,1,NaN
16,repulsive,trump,body,True,False,0,NaN
17,gross,trump,body,True,True,1,NaN
18,nasty,trump,body,True,True,2,NaN
19,wig,trump,body,True,False,2,NaN
20,snorlax,trump,body,False,False,1,NaN
21,creature,trump,body,True,True,1,NaN
22,confused,trump,mind,True,True,2,NaN
23,cooked,trump,mind,True,False,7,NaN
24,unhinged,trump,mind,True,True,4,NaN
25,unstable,trump,mind,True,True,3,NaN
26,insane,trump,mind,True,True,1,NaN
27,mad,trump,mind,True,True,4,NaN
28,crashing out,trump,mind,False,False,4,NaN
29,melts down,trump,mind,False,False,1,NaN
30,low energy,trump,mind,True,True,1,NaN
31,rambling,trump,mind,True,True,4,NaN
32,unwell,trump,mind,True,False,0,NaN
33,insecure,trump,mind,True,True,1,NaN
34,senile,trump,mind,False,False,1,NaN
35,deteriorating,trump,mind,True,False,2,NaN
36,useless,trump,mind,True,True,1,NaN
37,snoozing,trump,mind,False,False,1,NaN
38,sleepy,trump,mind,True,True,1,NaN
39,grandpa,trump,mind,True,False,1,NaN
40,old,trump,mind,True,False,5,NaN
41,oldest,trump,mind,True,False,0,NaN
42,80-year-old man,trump,mind,False,False,0,NaN
43,old as fart,trump,mind,False,False,1,NaN
44,can't read,trump,mind,True,True,1,NaN
45,dumb,trump,mind,True,True,1,NaN
46,stupid,trump,mind,True,True,3,NaN
47,weird,trump,mind,True,True,7,NaN
48,mess,trump,mind,True,False,3,NaN
49,sad sack,trump,mind,True,True,1,NaN
50,chopped,trump,mind,False,False,4,NaN
51,unc,trump,mind,False,False,1,NaN
52,mogged,trump,mind,False,False,6,NaN
53,evil,trump,morals,True,True,6,NaN
54,vile,trump,morals,True,True,0,NaN
55,predator,trump,morals,True,False,2,NaN
56,rat,trump,morals,True,True,0,NaN
57,traitor,trump,morals,True,True,0,NaN
58,convicted felon,trump,morals,False,False,5,NaN
59,wannabe dictator,trump,morals,False,False,1,NaN
60,looter,trump,morals,False,False,0,NaN
61,loser,trump,morals,True,True,4,NaN
62,liar,trump,morals,True,True,1,NaN
63,worst,trump,morals,True,True,8,NaN
64,disgusting,trump,morals,True,True,4,NaN
65,chud,trump,morals,False,False,12,NaN
66,fat chud,trump,morals,False,False,8,NaN
67,true chud,trump,morals,False,False,2,NaN
68,fat little chud,trump,morals,False,False,1,NaN
69,horny,trump,morals,False,False,1,NaN
70,snowflake,trump,morals,False,False,1,NaN
71,chicken,trump,morals,True,False,1,NaN
72,flop,trump,morals,True,True,3,NaN
73,spooky,trump,morals,False,False,1,NaN
74,haunted,trump,morals,False,False,1,NaN
75,nightmare,trump,morals,True,False,3,NaN
76,sleep-paralysis demon,trump,morals,False,False,0,NaN
77,resident evil,trump,morals,False,False,1,NaN
78,loony bin,trump,morals,False,False,0,NaN
79,diabolical,trump,morals,False,False,0,NaN
80,epstein's bff,trump,morals,False,False,0,NaN
81,jealous,trump,morals,True,True,1,NaN
82,tacky,trump,morals,True,False,2,NaN
83,tacky gold,trump,morals,False,False,1,NaN
84,pigging out,trump,morals,False,False,0,NaN
85,jobless,trump,morals,True,False,1,NaN
86,bootlicker,vance,subservience,False,False,3,NaN
87,ugly bootlicker,vance,subservience,False,False,1,NaN
88,sellout,vance,subservience,True,True,0,NaN
89,irrelevant,vance,subservience,True,True,1,NaN
90,negative aura,vance,subservience,False,False,0,NaN
91,jd-chan,vance,subservience,False,False,1,NaN
92,poor,vance,subservience,True,True,3,NaN
93,creep,vance,subservience,True,True,1,NaN
94,concerning,vance,subservience,True,False,1,NaN
95,owned,vance,subservience,True,True,1,NaN

## §5 — Do these words show up on the RNC feed too?

If the RNC uses the same words in its own voice, the vocabulary isn't uniquely Democratic. I search only the RNC's own-voice lines (caption or on-screen text, not songs or quoted clips). A raw word-match over-counts — the RNC quoting a Democrat, or an idiom like "worst" — so treat these as the screen; the genuine reuses are fewer, confirmed by hand.

In [11]:

OWN = ["caption", "overlay", "meme_text"]
rnc = dunks[(dunks["account"] == "republicans") & (dunks["source"].isin(OWN))]
rnc_text = rnc["dunk_line"].fillna("").str.lower()

hits = []
for term in curated["term"].unique():
    m = rnc_text.str.contains(rf"\b{term}\b", regex=True)
    if m.any():
        hits.append({"term": term, "rnc_own_voice_hits": int(m.sum()),
                     "example": rnc.loc[m, "dunk_line"].iloc[0]})
pd.DataFrame(hits).sort_values("rnc_own_voice_hits", ascending=False).reset_index(drop=True)

       term  rnc_own_voice_hits                                    example
0    stupid                   4              This stupid freaking red hat!
1       fat                   1         HIS STUPIDITY AND FAT ASS WHEEZING
2  confused                   1                                   CONFUSED
3       mad                   1                                   Stay mad
4      dumb                   1  DUMB MOTHERF***** DIDN'T DESERVE TO LIVE.
5    mogged                   1                                     mogged
6     worst                   1    Trump derangement syndrome at its worst